# Generated by Django 3.1 on 2023-10-19 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_joined',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
