# Generated by Django 3.1 on 2023-10-19 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231020_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_joined',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
