# Generated by Django 3.1 on 2023-10-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231020_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_joined',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
